exports.CONSTANTES_TORTAS = {
  /* Tortas redondas */
  TORTA_BISCOCHO_15_REDONDA : "Torta biscocho para 15 personas redonda",
  TORTA_BISCOCHO_20_REDONDA : "Torta biscocho para 20 personas redonda",
  TORTA_BISCOCHO_30_REDONDA : "Torta biscocho para 30 personas redonda",
  TORTA_BISCOCHO_40_REDONDA : "Torta biscocho para 40 personas redonda",
  TORTA_BISCOCHO_50_REDONDA : "Torta biscocho para 50 personas redonda",
  /* Tortas rectangulares */
  TORTA_BISCOCHO_15_REECTANGULAR : "Torta biscocho para 15 personas rectangular",
  TORTA_BISCOCHO_30_REECTANGULAR : "Torta biscocho para 30 personas rectangular",
  TORTA_BISCOCHO_40_REECTANGULAR : "Torta biscocho para 40 personas rectangular",
  TORTA_BISCOCHO_60_REECTANGULAR : "Torta biscocho para 60 personas rectangular",
  /* Tortas especiales */
  TORTA_ESPECIAL_12_PANQUEQUE : "Torta especial para 12 personas panqueque",
  TORTA_ESPECIAL_20_PANQUEQUE : "Torta especial para 20 personas panqueque",
  TORTA_ESPECIAL_30_PANQUEQUE : "Torta especial para 30 personas panqueque",
  TORTA_ESPECIAL_15_HOJARASCA_MILHOJA : "Torta especial para 15 personas hojarasca/milhoja",
  TORTA_ESPECIAL_20_HOJARASCA_MILHOJA : "Torta especial para 20 personas hojarasca/milhoja",
  TORTA_ESPECIAL_30_HOJARASCA_MILHOJA : "Torta especial para 30 personas hojarasca/milhoja",
  /* Banquetería dulce */
  REPOLLITOS : "Repollos",
  MIX_DULCE_TRADICIONAL : "Mix dulce tradicional (brownies, repollitos, brazo de reina)",
  MIX_DULCE_ESPECIAL : "Mix dulce especial (repollitos, mini pie de limón, maicenitos)",
  MIX_DULCE_ESTACION : "Mix dulce estación (brownie limón, tartaleta de fruta, pie de chocolate)",
  CAJA_DULCE_1 : "caja dulce 1 (brownie, pie limón, maicenitos)",
  CAJA_DULCE_2 : "caja dulce 2 (brownie, repollitos, brazo reina)",
  CAJA_DULCE_3 : "caja dulce 3 (brownie limón, pie de chocolate, maicenitos)",
  MINI_POSTRES : "Mini postres",
  /* Banquetería salada */
  EMPANADAS_SURTIDAS : "Empanaditas surtidas",
  EMPANADAS_VEGETARIANAS : "Empanaditas vegetarianas",
  TAPADITOS_SURTIDOS : "Tapaditos surtidos",
  CANAPES_SURTIDOS : "Canapes surtidos",
  CROSTINIS_SURTIDOS : "Crostinis surtidos",
  MINI_PIZZAS : "Mini pizzas",
  MINI_BROCHETAS_POLLO : "Mini brochetas de pollo",
  MINI_CHAPARRITAS: "Mini chaparritas",
  MIX_SALADO: "Mix salado (empanadas, crostinis , mini pizzas)",
  CAJA_SALADA_1: "Caja salada 1 (empanadas, tapaditos, mini pizzas)",
  CAJA_SALADA_2: "Caja salada 2 (empanadas, crostinis surtidos)",
  MINI_QUICHE_SURTIDO: "Mini quiche surtidos",
  TAPADITOS_PREMUIM_SURTIDO: "Tapaditos premium surtidos",
  /* Evento */
  EVENTO: "Evento",
};